# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: manasiphand2005@gmail.com
author_name: manasiphand
contract_name: zkp_vault
deployment_language: python
preset_name: production
project_name: zkp_vault-contracts

