# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: manasiphand2005@gmail.com
author_name: manasiphand
cloud_provider: vercel
contract_name: zkp_vault
deployment_language: python
preset_name: production
project_name: zkp_vault

